import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import sharp from 'sharp';

import {
  grassVarieties,
  type GrassVarietyId,
} from '../src/design/grass';
import { renderDetailedGrassSvg } from '../src/design/renderDetailedGrass';
import type { GrowthLevel } from '../src/types/garden';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const assetsDirectory = join(root, 'assets/widget-grass');
const manifestPath = join(root, 'src/design/generatedWidgetGrassAssets.ts');
const levels: readonly GrowthLevel[] = [0, 1, 2, 3, 4];

async function writeIfChanged(path: string, contents: Buffer | string): Promise<void> {
  const next = Buffer.isBuffer(contents) ? contents : Buffer.from(contents);
  const current = await readFile(path).catch(() => null);
  if (current?.equals(next)) return;
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, next);
}

function assetFingerprint(variety: GrassVarietyId, level: GrowthLevel): string {
  const svg = renderDetailedGrassSvg(level, { variety });
  return createHash('sha256').update(svg).digest('hex').slice(0, 10);
}

interface GeneratedAsset {
  filename: string;
  fingerprint: string;
}

async function generateVariety(variety: GrassVarietyId): Promise<readonly GeneratedAsset[]> {
  return Promise.all(
    levels.map(async (level) => {
      const fingerprint = assetFingerprint(variety, level);
      const filename = `${variety}-level-${level}-${fingerprint}.png`;
      const outputPath = join(assetsDirectory, filename);
      const svg = renderDetailedGrassSvg(level, { variety });
      const png = await sharp(Buffer.from(svg)).resize(128, 128).png().toBuffer();
      await writeIfChanged(outputPath, png);
      return { filename, fingerprint };
    }),
  );
}

async function main(): Promise<void> {
  const varieties = Object.keys(grassVarieties) as GrassVarietyId[];
  const generated = await Promise.all(
    varieties.map(async (variety) => [variety, await generateVariety(variety)] as const),
  );
  const expectedFiles = new Set(
    generated.flatMap(([, assets]) => assets.map(({ filename }) => filename)),
  );
  const existingFiles = await readdir(assetsDirectory);
  await Promise.all(
    existingFiles
      .filter((filename) => filename.endsWith('.png') && !expectedFiles.has(filename))
      .map((filename) => unlink(join(assetsDirectory, filename))),
  );

  const manifest = `// Generated by scripts/generate-grass-assets.ts. Do not edit.
import type { GrassVarietyId } from './grass';

interface WidgetGrassAsset {
  fingerprint: string;
  module: number;
}

export const widgetGrassAssets: Record<GrassVarietyId, readonly WidgetGrassAsset[]> = {
${generated
  .map(([variety, assets]) => {
    const entries = assets
        .map(
          ({ filename, fingerprint }) =>
            `    { fingerprint: ${JSON.stringify(fingerprint)}, module: require(${JSON.stringify(
              relative(dirname(manifestPath), join(assetsDirectory, filename)).replaceAll(
                '\\',
                '/',
              ),
            )}) },`,
        )
        .join('\n');
    return `  ${JSON.stringify(variety)}: [\n${entries}\n  ],`;
  })
  .join('\n')}
};
`;
  await writeIfChanged(manifestPath, manifest);
}

void main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
