// Generated by scripts/generate-grass-assets.ts. Do not edit.
import type { GrassVarietyId } from './grass';

interface WidgetGrassAsset {
  fingerprint: string;
  module: number;
}

export const widgetGrassAssets: Record<GrassVarietyId, readonly WidgetGrassAsset[]> = {
  "classic": [
    { fingerprint: "69ba951995", module: require("../../assets/widget-grass/classic-level-0-69ba951995.png") },
    { fingerprint: "082583ca8a", module: require("../../assets/widget-grass/classic-level-1-082583ca8a.png") },
    { fingerprint: "f2d1455f26", module: require("../../assets/widget-grass/classic-level-2-f2d1455f26.png") },
    { fingerprint: "52e433e53e", module: require("../../assets/widget-grass/classic-level-3-52e433e53e.png") },
    { fingerprint: "dde83bf0be", module: require("../../assets/widget-grass/classic-level-4-dde83bf0be.png") },
  ],
};
